$(document).ready(function(){
  $('#showChart1').click(function(){
    $('#chart1').removeClass('d-none');
    $('#chart2').addClass('d-none');
    $('#chart3').addClass('d-none');
    $('#chart4').addClass('d-none');
    $('#chart5').addClass('d-none');
    $('#showChart1').addClass('active');
    $('#showChart2').removeClass('active');
    $('#showChart3').removeClass('active');
    $('#showChart4').removeClass('active');
    $('#showChart5').removeClass('active');
  });

  $('#showChart2').click(function(){
    $('#chart1').addClass('d-none');
    $('#chart2').removeClass('d-none');
    $('#chart3').addClass('d-none');
    $('#chart4').addClass('d-none');
    $('#chart5').addClass('d-none');
    $('#showChart1').removeClass('active');
    $('#showChart2').addClass('active');
    $('#showChart3').removeClass('active');
    $('#showChart4').removeClass('active');
    $('#showChart5').removeClass('active');
  });

  $('#showChart3').click(function(){
    $('#chart1').addClass('d-none');
    $('#chart2').addClass('d-none');
    $('#chart3').removeClass('d-none');
    $('#chart4').addClass('d-none');
    $('#chart5').addClass('d-none');
    $('#showChart1').removeClass('active');
    $('#showChart2').removeClass('active');
    $('#showChart3').addClass('active');
    $('#showChart4').removeClass('active');
    $('#showChart5').removeClass('active');
  });

  $('#showChart4').click(function(){
    $('#chart1').addClass('d-none');
    $('#chart2').addClass('d-none');
    $('#chart3').addClass('d-none');
    $('#chart4').removeClass('d-none');
    $('#chart5').addClass('d-none');
    $('#showChart1').removeClass('active');
    $('#showChart2').removeClass('active');
    $('#showChart3').removeClass('active');
    $('#showChart4').addClass('active');
    $('#showChart5').removeClass('active');
  });

  $('#showChart5').click(function(){
    $('#chart1').addClass('d-none');
    $('#chart2').addClass('d-none');
    $('#chart3').addClass('d-none');
    $('#chart4').addClass('d-none');
    $('#chart5').removeClass('d-none');
    $('#showChart1').removeClass('active');
    $('#showChart2').removeClass('active');
    $('#showChart3').removeClass('active');
    $('#showChart4').removeClass('active');
    $('#showChart5').addClass('active');
  });
});
